### PR TITLE
feat(GCR): Add shell script to create GCR account

### PR DESCRIPTION
**Pull request by Tangeek59**
I'm currently following spinnaker documentation for adding GCR repositories (https://www.spinnaker.io/setup/install/providers/docker-registry/#google-container-registry)

But I'm going to have multiple projects to connect with my spinnaker instance, so I've created a shell file inspired by the `add_gae_account.sh` one.

### CODE REVIEW

**Comment by demobox** [comment]
Thanks Tanguy! Looking forward to taking a look at this one.

**Comment by Tangeek59** [comment]
After some complementary tests in local, I have some issues.

The clouddriver component doesn't start with `401 unauthorized` when trying to contact the docker registry.

Maybe I could write another version using a json token, as described in the spinnaker documentation, rather than promoting rights to the spinnaker service account.

What do you think of it ?

**Comment by demobox** [comment]
> Maybe I could write another version using a json token, as described in the spinnaker documentation, 

I see you added a commit; is this working now?

Regarding integration with GCR in general: we usually recommend using Pub/sub to trigger Spinnaker pipelines from GCR vs. using Docker registry accounts as this means Spinnaker does not have to poll GCR.

Is there any particular reason you are considering Docker registry accounts for this?

**Comment by Tangeek59** [comment]
I'm new to spinnaker and thought that using a Docker registry was the best way to trigger pipelines. But it seems that i was wrong, thanks for the tip ;)

If you think that this feature is not needed, you can close the PR.

**Comment by demobox** [comment]
> I'm new to spinnaker and thought that using a Docker registry was the best way to trigger pipelines. But it seems that i was wrong, thanks for the tip ;)

Pushes to container registries are definitely a common way to trigger a deployment pipeline. What I meant is that, for GCR specifically, Spinnaker has two ways to detect new images or image tags:

* it can poll the registry, using a Docker registry account
* it can be configured to [receive a Pub/sub message](https://www.spinnaker.io/setup/triggers/google/#receiving-messages-from-google-container-registry-gcr) whenever a container image or tag is pushed (this is a GCR-specific feature that doesn't work for other container registry types)

For GCR, we generally recommend Pub/sub since it avoids the need to poll the registry.

**Comment by Tangeek59** [comment]
> Pushes to container registries are definitely a common way to trigger a deployment pipeline.

Yes, I was aware about this. 

> For GCR, we generally recommend Pub/sub since it avoids the need to poll the registry.

This is where I was wrong, I didn't remembered that there was a pub/sub option for those types of trigger. Definitely a better way to handle this ;)

**Pull request closed without merging**
